# fly.toml app configuration file generated for web-speed-hackathon-2025-bitter-frog-2828 on 2025-03-23T16:38:31+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'web-speed-hackathon-2025-bitter-frog-2828'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
