packages:
  - ./workspaces/configs
  - ./workspaces/schema
  - ./workspaces/client
  - ./workspaces/server
  - ./workspaces/test
onlyBuiltDependencies:
  - bcrypt
ignoredBuiltDependencies:
  - core-js
  - esbuild
