services:
  - type: web
    runtime: node
    name: wsh-2025-server
    buildCommand: pnpm install
    startCommand: pnpm start
    rootDir: workspaces/server
    envVars:
      - key: NODE_ENV
        value: production