import * as openapiSchema from '@wsh-2025/schema/src/openapi/schema';

export const getChannelsRequestQuery = openapiSchema.getChannelsRequestQuery;
export const getChannelsResponse = openapiSchema.getChannelsResponse;
export const getChannelByIdRequestParams = openapiSchema.getChannelByIdRequestParams;
export const getChannelByIdResponse = openapiSchema.getChannelByIdResponse;
export const getEpisodesRequestQuery = openapiSchema.getEpisodesRequestQuery;
export const getEpisodesResponse = openapiSchema.getEpisodesResponse;
export const getEpisodeByIdRequestParams = openapiSchema.getEpisodeByIdRequestParams;
export const getEpisodeByIdResponse = openapiSchema.getEpisodeByIdResponse;
export const getSeriesRequestQuery = openapiSchema.getSeriesRequestQuery;
export const getSeriesResponse = openapiSchema.getSeriesResponse;
export const getSeriesByIdRequestParams = openapiSchema.getSeriesByIdRequestParams;
export const getSeriesByIdResponse = openapiSchema.getSeriesByIdResponse;
export const getTimetableRequestQuery = openapiSchema.getTimetableRequestQuery;
export const getTimetableResponse = openapiSchema.getTimetableResponse;
export const getProgramsRequestQuery = openapiSchema.getProgramsRequestQuery;
export const getProgramsResponse = openapiSchema.getProgramsResponse;
export const getProgramByIdRequestParams = openapiSchema.getProgramByIdRequestParams;
export const getProgramByIdResponse = openapiSchema.getProgramByIdResponse;
export const getRecommendedModulesRequestParams = openapiSchema.getRecommendedModulesRequestParams;
export const getRecommendedModulesResponse = openapiSchema.getRecommendedModulesResponse;
export const signInRequestBody = openapiSchema.signInRequestBody;
export const signInResponse = openapiSchema.signInResponse;
export const signUpRequestBody = openapiSchema.signUpRequestBody;
export const signUpResponse = openapiSchema.signUpResponse;
export const getUserResponse = openapiSchema.getUserResponse;
